[build]
  command = "npm --prefix obtenirrembourssement run build"
  publish = "obtenirrembourssement/dist"

[functions]
  directory = "obtenirrembourssement/netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
