[build]
  command = "npm --prefix rembous run build"
  publish = "rembous/dist"

[functions]
  directory = "rembous/netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
